apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: argocd-hugo
  name: hugo-website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo-website
      namespace: default
  template:
    metadata:
      labels:
        app: hugo-website
    spec:
      containers:
        - image: 'hugo-website:latest'
          name: hugo-website
          ports:
            - containerPort: 80
